# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Release Creator
        # You may pin to the exact commit or the version.
        # uses: alice-biometrics/release-creator@776aae43916758e40fc9420eb85f5659994f4a3e
        uses: alice-biometrics/release-creator@v1.0.4
        with:
          # GitHub token
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          # New release version
          version: inherit
          # New release description
          description: inherit
          # Git repository where the release will be create
          repo: this# optional, default is this
          # Git repository branch where the release will be create
          branch: master # optional, default is master
          # Define if new release is a draft or not
          draft: false# optional, default is false
          # Define if new release is a prerelease or not
          prerelease: flase # optional, default is false
      - name: Zip Release
        # You may pin to the exact commit or the version.
        # uses: TheDoctor0/zip-release@a1afcab9c664c9976ac398fa831eac67bed1eb0e
        uses: TheDoctor0/zip-release@0.4.1
        with:
          # Filename for archive
          filename: blood-bowl-fvtt.zip
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "blood-bowl-fvtt.zip"
            token: ${{ secrets.GITHUB_TOKEN }}
          
          
          
          
          
          
          
          
          
          
